import type { ActionDef } from "./game.ts";

export const ACTION_DEFS: ActionDef[] = [
  {
    id: "farm",
    name: "Farm",
    description: "Work the land. Produces food each year.",
    skill: "farming",
    category: "resource",
    baseDuration: 100,
    unlockLevel: 0,
  },
  {
    id: "gather_materials",
    name: "Gather Materials",
    description: "Collect wood, stone, and basic materials.",
    skill: "building",
    category: "resource",
    baseDuration: 80,
    unlockLevel: 0,
  },
  {
    id: "build_hut",
    name: "Build Hut",
    description: "Shelter for population. Increases pop capacity. Costs 20 materials.",
    skill: "building",
    category: "building",
    baseDuration: 120,
    unlockLevel: 2,
    materialCost: 20,
  },
  {
    id: "build_granary",
    name: "Build Granary",
    description: "Stores extra food. Critical for winter prep. Costs 50 materials.",
    skill: "building",
    category: "building",
    baseDuration: 200,
    unlockLevel: 5,
    materialCost: 50,
  },
  {
    id: "build_wall",
    name: "Build Wall",
    description: "Fortify defenses. Adds wall defense against raiders. Costs 30 materials.",
    skill: "building",
    category: "building",
    baseDuration: 160,
    unlockLevel: 4,
    materialCost: 30,
  },
  {
    id: "train_militia",
    name: "Train Militia",
    description: "Raise military strength. Needed to repel raiders.",
    skill: "military",
    category: "military",
    baseDuration: 150,
    unlockLevel: 0,
  },
  {
    id: "research_tools",
    name: "Research Tools",
    description: "Improve technology. Each completion boosts all output by 10%.",
    skill: "research",
    category: "research",
    baseDuration: 180,
    unlockLevel: 0,
  },
  {
    id: "scout",
    name: "Scout",
    description: "Explore surroundings. Small military & research XP.",
    skill: "military",
    category: "military",
    baseDuration: 60,
    unlockLevel: 3,
  },
  {
    id: "cure_food",
    name: "Cure Food",
    description: "Prepare and cure food for long-term storage. Converts up to 100 food into preserved food that spoils much slower.",
    skill: "research",
    category: "resource",
    baseDuration: 140,
    unlockLevel: 5,
  },
  {
    id: "winter_hunt",
    name: "Winter Hunt",
    description: "Hunt and forage for scarce winter life. Produces a small amount of food year-round.",
    skill: "military",
    category: "resource",
    baseDuration: 100,
    unlockLevel: 0,
  },
];

export function getActionDef(id: string): ActionDef | undefined {
  return ACTION_DEFS.find((a) => a.id === id);
}
