import type { ActionDef } from "./game.ts";

export const ACTION_DEFS: ActionDef[] = [
  {
    id: "farm",
    name: "Farm",
    description: "Work the land. Produces food each year.",
    skill: "farming",
    category: "resource",
    baseDuration: 100,
    unlockLevel: 0,
  },
  {
    id: "gather_wood",
    name: "Gather Wood",
    description: "Collect wood from nearby forests.",
    skill: "building",
    category: "resource",
    baseDuration: 80,
    unlockLevel: 0,
  },
  {
    id: "build_hut",
    name: "Build Hut",
    description: "Shelter for population. Increases pop capacity. Costs 20 wood.",
    skill: "building",
    category: "building",
    baseDuration: 120,
    unlockLevel: 1,
    woodCost: 20,
  },
  {
    id: "build_granary",
    name: "Build Granary",
    description: "Stores extra food. Critical for winter prep. Diminishing returns. Costs 50 wood.",
    skill: "building",
    category: "building",
    baseDuration: 300,
    unlockLevel: 5,
    woodCost: 50,
  },
  {
    id: "build_barracks",
    name: "Build Barracks",
    description: "Military training grounds. Unlocks militia training. Each barracks ×1.15 military XP/tick. Costs 25 wood.",
    skill: "building",
    category: "building",
    baseDuration: 200,
    unlockLevel: 2,
    woodCost: 25,
  },
  {
    id: "build_smokehouse",
    name: "Build Smokehouse",
    description: "Smoke and cure food to slow spoilage. Each smokehouse ×0.90 spoilage rate. Costs 15 wood.",
    skill: "building",
    category: "building",
    baseDuration: 260,
    unlockLevel: 3,
    woodCost: 15,
  },
  {
    id: "build_wall",
    name: "Build Wall",
    description: "Fortify defenses. Each wall boosts defense with diminishing returns. Costs 30 wood.",
    skill: "building",
    category: "building",
    baseDuration: 160,
    unlockLevel: 4,
    woodCost: 30,
  },
  {
    id: "train_militia",
    name: "Train Militia",
    description: "Raise military strength. Needed to repel raiders.",
    skill: "military",
    category: "military",
    baseDuration: 110,
    unlockLevel: 0,
    requiredBarracks: 1,
  },
  {
    id: "research_tools",
    name: "Improved Tools",
    description: "Better tool-making. +15% wood gathering output.",
    skill: "research",
    category: "research",
    baseDuration: 140,
    unlockLevel: 0,
  },
  {
    id: "research_irrigation",
    name: "Irrigation",
    description: "Water management for crops. +15% food from farming.",
    skill: "research",
    category: "research",
    baseDuration: 150,
    unlockLevel: 0,
    requiredTech: "research_tools",
  },
  {
    id: "research_storage",
    name: "Food Preservation",
    description: "Techniques to keep food longer. +100 food storage capacity.",
    skill: "research",
    category: "research",
    baseDuration: 170,
    unlockLevel: 5,
  },
  {
    id: "research_fortification",
    name: "Fortification",
    description: "Defensive engineering. Requires a wall. ×1.20 total defense.",
    skill: "research",
    category: "research",
    baseDuration: 190,
    unlockLevel: 4,
    woodCost: 10,
    requiredWalls: 1,
  },
  {
    id: "research_tactics",
    name: "Tactics",
    description: "Military strategy. +15% total military strength.",
    skill: "research",
    category: "research",
    baseDuration: 170,
    unlockSkill: "military",
    unlockLevel: 5,
  },
  {
    id: "scout",
    name: "Scout",
    description: "Explore surroundings. Small military & research XP.",
    skill: "military",
    category: "military",
    baseDuration: 60,
    unlockLevel: 3,
    requiredBarracks: 1,
  },
  {
    id: "cure_food",
    name: "Cure Food",
    description: "Prepare and cure food for long-term storage. Converts up to 100 food into preserved food that spoils much slower.",
    skill: "farming",
    category: "resource",
    baseDuration: 120,
    unlockLevel: 5,
    completionOnly: "building",
  },
  {
    id: "winter_hunt",
    name: "Winter Hunt",
    description: "Hunt and forage for scarce winter life. Produces a small amount of food year-round.",
    skill: "military",
    category: "resource",
    baseDuration: 100,
    unlockLevel: 0,
  },
];

export function getActionDef(id: string): ActionDef | undefined {
  return ACTION_DEFS.find((a) => a.id === id);
}
